name: Pre-release

on:
    push:
        branches:
            - main
        tags-ignore:
            - "*"

jobs:
    build-and-prerelease:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential cmake

            - name: Build with Makefile
              run: make

            - name: Archive binary
              run: |
                  mkdir -p artifacts
                  cp build/dronesim artifacts/

            - name: Create pre-release
              uses: softprops/action-gh-release@v2
              with:
                  name: "Pre-release $(date +'%Y-%m-%d %H:%M:%S')"
                  prerelease: true
                  files: artifacts/*
